query GetUserData{
    user{
        name
        phonenumber
        subscriptiontype
    }
    userCards{
        id
        name
        balance
        limit
        iscredit
    }
    userCustomCategories{
        id
        name
        type
        icon
    }
}